backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - file: 'content/pages/home/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
          - {
              label: 'Call to Actions',
              name: 'callToActions',
              required: true,
              widget: 'object',
              fields:
                [
                  {
                    label: 'First CTA',
                    name: 'firstCTA',
                    required: true,
                    widget: 'object',
                    fields:
                      [
                        { label: 'Text', name: 'text', widget: 'string' },
                        {
                          label: 'Link Type',
                          name: 'linkType',
                          widget: 'select',
                          options: ['internal', 'external'],
                        },
                        {
                          label: 'Link URL',
                          name: 'linkURL',
                          widget: 'string',
                          hint: 'Use a relative URL (e.g. /about) if the link is an internal link.',
                        },
                      ],
                  },
                ],
            }
          - {
              label: 'SEO & Meta',
              name: 'seo',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Browser Tab Title',
                    name: 'browserTitle',
                    widget: 'string',
                  },
                  { label: 'Title', name: 'title', widget: 'string' },
                  {
                    label: 'Description',
                    name: 'description',
                    widget: 'string',
                  },
                ],
            }
